"""Render a Case into the same markdown shape as the hand-written essays, so the
documents become reproducible outputs of the engine rather than prose artifacts.
"""

from __future__ import annotations

from .engine import Analysis, analyze
from .lenses import LENSBOOK, BY_KEY
from .model import Case, Function, Tradition, Verdict

_VERDICT_GLOSS = {
    "endorse": "endorses",
    "condemn": "condemns",
    "mixed": "is divided on",
    "na": "supplies no standard to judge",
}
_GRIP_GLOSS = {1: "strains against", 2: "partly grips", 3: "firmly grips"}


def _functions_line(t: Tradition) -> str:
    if t.is_null:
        return "_null / critical (neither significance nor warrant)_"
    return "_" + ", ".join(sorted(f.value for f in t.functions)) + "_"


def render_case(case: Case, lensbook: tuple[Tradition, ...] = LENSBOOK) -> str:
    a: Analysis = analyze(case, lensbook)
    out: list[str] = []
    out.append(f"# {case.title} Across Twenty-Seven Traditions\n")
    out.append(f"_{case.summary}_\n")
    out.append("## Profile\n")
    out.append(
        f"- Significance axis: **{a.significance:+.2f}** "
        f"({'high' if a.significance_high else 'low'})\n"
        f"- Warrant axis: **{'n/a' if a.warrant is None else f'{a.warrant:+.2f}'}** "
        f"({a.warrant_band})\n"
        f"- Quadrant: **{a.quadrant}**\n"
        f"- Failure modes tripped: {len(a.failure_tripped_keys)}/{len(lensbook)} "
        f"({a.failure_trip_rate:.0%})\n"
    )
    if a.warrant_lenses_condemning:
        names = ", ".join(BY_KEY[k].name for k in a.warrant_lenses_condemning)
        out.append(f"- Warrant lenses condemning: {names}\n")
    if a.provisional_keys:
        names = ", ".join(BY_KEY[k].name for k in a.provisional_keys)
        out.append(f"- Provisional readings (need primary sources): {names}\n")
    out.append("\n---\n")

    for t in lensbook:
        r = case.reading_for(t.key)
        assert r is not None
        out.append(f"\n## {t.numeral}. {t.name}\n")
        out.append(f"*{t.question}*  \n")
        out.append(f"{_functions_line(t)}\n")
        verdict_clause = ""
        if t.does(Function.WARRANT):
            verdict_clause = f" It {_VERDICT_GLOSS[r.verdict.value]} the act."
        flag = " It trips the tradition's failure mode." if r.failure_tripped else ""
        out.append(
            f"\nThe lens {_GRIP_GLOSS[int(r.grip)]} the act.{verdict_clause}{flag} "
            f"{r.note}\n"
        )
    out.append("\n---\n")
    out.append("\n_Generated by meaning-assay from authored, citable readings. "
               "Function tags and verdicts are contestable data; edit the case "
               "and lensbook and re-render._\n")
    return "".join(out)


def render_pair_summary(pair) -> str:
    """pair: pairs.PairAnalysis"""
    lines = [
        f"# Contrast: {pair.a_key} vs {pair.b_key}\n",
        f"\n**Finding: {pair.finding}.**\n",
        f"\n- Significance: {pair.significance_a:+.2f} -> {pair.significance_b:+.2f} "
        f"(delta {pair.significance_delta:+.2f}); stable: {pair.significance_stable}\n",
        f"- Warrant: "
        f"{'n/a' if pair.warrant_a is None else f'{pair.warrant_a:+.2f}'} -> "
        f"{'n/a' if pair.warrant_b is None else f'{pair.warrant_b:+.2f}'}; "
        f"inverts: {pair.warrant_inverts}\n",
        f"- Quadrants: {pair.quadrant_a} -> {pair.quadrant_b}\n",
    ]
    if pair.verdict_switchers:
        names = ", ".join(BY_KEY[k].name for k in pair.verdict_switchers)
        lines.append(f"- Warrant lenses that flip endorse/condemn: {names}\n")
    if pair.polarity_switchers:
        names = ", ".join(BY_KEY[k].name for k in pair.polarity_switchers)
        lines.append(f"- Significance lenses whose polarity flips: {names}\n")
    return "".join(lines)
